# Generated by Django 4.0.5 on 2022-06-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musical_genre',
            options={'verbose_name': 'genre musical', 'verbose_name_plural': 'generes musicales'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
