# Generated by Django 4.0.5 on 2022-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_musical_genre_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SKU',
            field=models.CharField(default=3, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
