# Generated by Django 4.0.4 on 2022-07-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.musical_genre'),
            preserve_default=False,
        ),
    ]
